import { LocationItem } from './geo.types';

export const LOCATIONS_REGISTRY: LocationItem[] = [
  // ==========================================
  // 1. GUJARAT CITIES
  // ==========================================
  {
    slug: 'ahmedabad',
    city: 'Ahmedabad',
    state: 'Gujarat',
    country: 'India',
    countryCode: 'IN',
    region: 'Gujarat',
    regionCode: 'IN-GJ',
    postalCode: '382330',
    coordinates: { latitude: 23.0754, longitude: 72.6560 },
    popular: true,
    headlineTitle: 'We build websites, apps and custom software for businesses in',
    headlineHighlight: 'Ahmedabad',
    subheadline: 'As an established IT agency headquartered in Ahmedabad with 7+ years of engineering excellence, we help local businesses launch modern websites, mobile apps, and scalable digital systems.',
    aboutText: "We are an Ahmedabad-based technology agency. Over the last 7+ years, we have delivered 350+ digital solutions for leading enterprises, startups, and growing commercial brands across Ahmedabad and Gujarat.",
    metaTitle: 'Web Development & Custom Software Company in Ahmedabad | TryangleTech',
    metaDescription: 'Top-rated IT & Web Development company in Ahmedabad. We build custom websites, iOS/Android mobile apps, and custom software systems with 350+ delivered projects.',
    keywords: [
      'Web Development Ahmedabad',
      'Software Company in Ahmedabad',
      'Mobile App Development Ahmedabad',
      'IT Company Nava Naroda',
      'Website Design Agency Ahmedabad',
      'Next.js Developers Ahmedabad',
      'Flutter App Company Gujarat'
    ],
    faqs: [
      {
        q: 'Why hire TryangleTech for web and software development in Ahmedabad?',
        a: 'We are physically based in Ahmedabad with 7+ years of track record, delivering 350+ projects. You get a dedicated point of contact, direct communication, and zero technical jargon.',
      },
      {
        q: 'What is the typical turnaround time for a website or app in Ahmedabad?',
        a: 'A standard custom website takes 2 to 4 weeks, while complex mobile apps or enterprise software take 4 to 8 weeks.',
      },
    ],
  },
  {
    slug: 'surat',
    city: 'Surat',
    state: 'Gujarat',
    country: 'India',
    countryCode: 'IN',
    region: 'Gujarat',
    regionCode: 'IN-GJ',
    postalCode: '395003',
    coordinates: { latitude: 21.1702, longitude: 72.8311 },
    popular: true,
    headlineTitle: 'Custom web development, mobile apps and software solutions in',
    headlineHighlight: 'Surat',
    subheadline: 'Empowering textile, diamond, e-commerce, and industrial businesses in Surat with bespoke web design, ERP software, and high-performance mobile applications.',
    aboutText: "We engineer high-converting websites and automated business software for companies in Surat. From diamond and textile manufacturing CRM systems to modern retail apps, we build technology tailored to your industry.",
    metaTitle: 'Best Web Development & Mobile App Company in Surat | TryangleTech',
    metaDescription: 'Leading web design and custom software development company serving Surat, Gujarat. Boost your business with high-speed websites, apps, and enterprise tools.',
    keywords: [
      'Web Development Company Surat',
      'Software Development Surat',
      'Mobile App Developers Surat',
      'E-commerce Website Design Surat',
      'IT Services Surat Gujarat',
      'Textile ERP Software Surat'
    ],
    faqs: [
      {
        q: 'Do you build custom software for Surat manufacturing and textile businesses?',
        a: 'Yes, we develop custom inventory software, order management portals, and e-commerce platforms tailored for Surat diamond, textile, and manufacturing enterprises.',
      },
      {
        q: 'Can we schedule in-person or online project discussions from Surat?',
        a: 'Absolutely. We provide dedicated project managers with seamless video meetings and on-demand milestone reviews.',
      },
    ],
  },
  {
    slug: 'vadodara',
    city: 'Vadodara',
    state: 'Gujarat',
    country: 'India',
    countryCode: 'IN',
    region: 'Gujarat',
    regionCode: 'IN-GJ',
    postalCode: '390001',
    coordinates: { latitude: 22.3072, longitude: 73.1812 },
    popular: true,
    headlineTitle: 'Premier software engineering and web application services in',
    headlineHighlight: 'Vadodara',
    subheadline: 'Delivering robust enterprise web portals, engineering automation tools, and mobile apps for pharmaceutical, chemical, and industrial leaders across Vadodara.',
    aboutText: "TryangleTech delivers state-of-the-art web applications and custom software engineering for Vadodara's thriving industrial and education sectors, backed by 7+ years of software delivery.",
    metaTitle: 'Web Development & Custom Software Engineering in Vadodara | TryangleTech',
    metaDescription: 'Reliable web development, mobile apps, and custom software company in Vadodara (Baroda). 350+ projects delivered with high performance and security.',
    keywords: [
      'Web Development Vadodara',
      'Software Company in Vadodara',
      'Mobile App Development Baroda',
      'IT Company Vadodara Gujarat',
      'Industrial Software Vadodara'
    ],
    faqs: [
      {
        q: 'What types of web applications do you build for Vadodara clients?',
        a: 'We specialize in Next.js web applications, client dashboards, custom ERP/CRM tools, and native iOS/Android mobile apps.',
      },
    ],
  },
  {
    slug: 'rajkot',
    city: 'Rajkot',
    state: 'Gujarat',
    country: 'India',
    countryCode: 'IN',
    region: 'Gujarat',
    regionCode: 'IN-GJ',
    postalCode: '360001',
    coordinates: { latitude: 22.3039, longitude: 70.8022 },
    popular: true,
    headlineTitle: 'Top-tier website design and mobile app development in',
    headlineHighlight: 'Rajkot',
    subheadline: 'Helping Saurashtra engineering manufacturers, jewelry exporters, and commercial businesses in Rajkot expand digitally with custom web and mobile technology.',
    aboutText: "We engineer high-impact digital solutions for Rajkot and the Saurashtra region. We build fast, mobile-friendly websites and automated software that converts visitors into customers.",
    metaTitle: 'Web Development & Mobile App Company in Rajkot | TryangleTech',
    metaDescription: 'Top-rated web development, mobile app development, and business software in Rajkot, Gujarat. 350+ projects delivered with proven ROI.',
    keywords: [
      'Web Development Rajkot',
      'Website Design Rajkot',
      'Software Development Company Rajkot',
      'Mobile App Developers Rajkot',
      'IT Agency Saurashtra'
    ],
    faqs: [
      {
        q: 'Do you provide post-launch support for businesses in Rajkot?',
        a: 'Yes, we provide ongoing maintenance, feature upgrades, security patches, and cloud hosting support.',
      },
    ],
  },
  {
    slug: 'gandhinagar',
    city: 'Gandhinagar',
    state: 'Gujarat',
    country: 'India',
    countryCode: 'IN',
    region: 'Gujarat',
    regionCode: 'IN-GJ',
    postalCode: '382010',
    coordinates: { latitude: 23.2156, longitude: 72.6369 },
    popular: false,
    headlineTitle: 'FinTech, SaaS and enterprise software development in',
    headlineHighlight: 'Gandhinagar & GIFT City',
    subheadline: 'Building next-generation web platforms, cloud software, and API integrations for GIFT City financial institutions and tech startups.',
    aboutText: "Serving Gandhinagar and GIFT City with enterprise-grade cloud architecture, compliant financial portals, and full-stack software solutions.",
    metaTitle: 'Software & Web Development in Gandhinagar & GIFT City | TryangleTech',
    metaDescription: 'FinTech and enterprise web software development for GIFT City and Gandhinagar startups and institutions.',
    keywords: [
      'GIFT City Software Company',
      'Web Development Gandhinagar',
      'Fintech App Development Gujarat',
      'IT Services Gandhinagar'
    ],
    faqs: [
      {
        q: 'Do you build cloud software for GIFT City financial companies?',
        a: 'Yes, we build secure, compliant cloud portals with modern encryption, API integrations, and robust database architectures.',
      },
    ],
  },

  // ==========================================
  // 2. INDIA METRO COMMERCIAL HUBS
  // ==========================================
  {
    slug: 'mumbai',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    countryCode: 'IN',
    region: 'India Metros',
    regionCode: 'IN-MH',
    postalCode: '400001',
    coordinates: { latitude: 19.0760, longitude: 72.8777 },
    popular: true,
    headlineTitle: 'High-growth websites, mobile apps and enterprise software in',
    headlineHighlight: 'Mumbai',
    subheadline: 'Partnering with Mumbai startups, financial brands, and retail leaders to deliver world-class digital applications that drive revenue and scale effortlessly.',
    aboutText: "From Bandra and BKC to Lower Parel and Andheri, we deliver high-performance Next.js web applications, Flutter mobile apps, and custom business automation tools for Mumbai enterprises.",
    metaTitle: 'Web Development & Custom Software Company in Mumbai | TryangleTech',
    metaDescription: 'Top web development and mobile app development agency for Mumbai businesses. Enterprise Next.js apps, cross-platform mobile apps, and custom software.',
    keywords: [
      'Web Development Company Mumbai',
      'Mobile App Development Mumbai',
      'Custom Software Development Mumbai',
      'Next.js Agency Mumbai',
      'IT Solutions BKC Mumbai'
    ],
    faqs: [
      {
        q: 'Why do Mumbai enterprises choose TryangleTech?',
        a: 'We combine agile sprint delivery with cost efficiency, transparent pricing, and 7+ years of experience delivering 350+ high-traffic digital applications.',
      },
    ],
  },
  {
    slug: 'pune',
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    countryCode: 'IN',
    region: 'India Metros',
    regionCode: 'IN-MH',
    postalCode: '411001',
    coordinates: { latitude: 18.5204, longitude: 73.8567 },
    popular: true,
    headlineTitle: 'Modern tech engineering and mobile application development in',
    headlineHighlight: 'Pune',
    subheadline: 'Engineering custom SaaS platforms, automotive portals, and high-conversion websites for Hinjewadi and Baner tech innovators.',
    aboutText: "We work with Pune's tech ecosystem to build scalable cloud backends, modern React/Next.js interfaces, and cross-platform mobile applications.",
    metaTitle: 'Custom Software & Mobile App Development Company in Pune | TryangleTech',
    metaDescription: 'Leading software development company serving Pune. We build custom websites, SaaS products, and mobile apps with speed and precision.',
    keywords: [
      'Web Development Pune',
      'Software Company in Pune',
      'Mobile App Development Pune',
      'SaaS Development Agency Pune',
      'React Native Pune'
    ],
    faqs: [
      {
        q: 'Can you help build an MVP for our Pune startup?',
        a: 'Yes, we specialize in launching feature-rich MVPs within 3 to 6 weeks with robust architecture ready for investor demonstrations.',
      },
    ],
  },
  {
    slug: 'bengaluru',
    city: 'Bengaluru',
    state: 'Karnataka',
    country: 'India',
    countryCode: 'IN',
    region: 'India Metros',
    regionCode: 'IN-KA',
    postalCode: '560001',
    coordinates: { latitude: 12.9716, longitude: 77.5946 },
    popular: true,
    headlineTitle: 'Full-stack software engineering and startup applications in',
    headlineHighlight: 'Bengaluru (Bangalore)',
    subheadline: 'Accelerating tech startups and enterprises in Koramangala, Indiranagar, and HSR Layout with scalable full-stack architectures and high-velocity development.',
    aboutText: "We deliver advanced web architectures, AI-integrated workflows, and native/hybrid mobile apps for companies across Bengaluru's tech corridor.",
    metaTitle: 'Web & Mobile App Development Company in Bengaluru (Bangalore) | TryangleTech',
    metaDescription: 'Premier full-stack web and mobile application engineering agency in Bengaluru. High-velocity Next.js, Flutter, and cloud software development.',
    keywords: [
      'Web Development Bengaluru',
      'Software Development Company Bangalore',
      'Mobile App Developers Bangalore',
      'Next.js Developers Bangalore',
      'Startup MVP Development Bengaluru'
    ],
    faqs: [
      {
        q: 'What tech stack do you recommend for high-scale applications in Bengaluru?',
        a: 'We leverage Next.js, React, Node.js, TypeScript, PostgreSQL, and AWS for lightning-fast performance and infinite scalability.',
      },
    ],
  },
  {
    slug: 'delhi-ncr',
    city: 'Delhi NCR',
    state: 'Delhi',
    country: 'India',
    countryCode: 'IN',
    region: 'India Metros',
    regionCode: 'IN-DL',
    postalCode: '110001',
    coordinates: { latitude: 28.6139, longitude: 77.2090 },
    popular: true,
    headlineTitle: 'Bespoke web development and digital enterprise software in',
    headlineHighlight: 'Delhi NCR & Gurgaon',
    subheadline: 'Building mission-critical business portals, D2C e-commerce stores, and custom software for Delhi, Gurgaon, and Noida businesses.',
    aboutText: "Partnering with Delhi NCR enterprises to build clean, fast, and converting digital products with transparent communication and guaranteed timelines.",
    metaTitle: 'Web Development & Custom Software Agency in Delhi NCR | TryangleTech',
    metaDescription: 'Trusted web design, mobile app, and software engineering company in Delhi, Gurgaon, and Noida. 350+ projects delivered.',
    keywords: [
      'Web Development Delhi NCR',
      'Software Company in Gurgaon',
      'Mobile App Development Noida',
      'Website Design Delhi',
      'IT Agency Delhi'
    ],
    faqs: [
      {
        q: 'Do you build custom D2C and B2B portals for Delhi NCR businesses?',
        a: 'Yes, we build custom e-commerce engines, wholesale order systems, and customer self-service portals.',
      },
    ],
  },
  {
    slug: 'hyderabad',
    city: 'Hyderabad',
    state: 'Telangana',
    country: 'India',
    countryCode: 'IN',
    region: 'India Metros',
    regionCode: 'IN-TG',
    postalCode: '500001',
    coordinates: { latitude: 17.3850, longitude: 78.4867 },
    popular: true,
    headlineTitle: 'Enterprise web systems and cross-platform mobile apps in',
    headlineHighlight: 'Hyderabad',
    subheadline: 'Delivering robust cloud software, healthcare platforms, and high-performance websites for HITEC City and Gachibowli businesses.',
    aboutText: "We bring 7+ years of engineering rigor to Hyderabad, building customized software applications that streamline business operations and captivate users.",
    metaTitle: 'Web Development & Custom Software in Hyderabad | TryangleTech',
    metaDescription: 'Leading web design and mobile app development company for Hyderabad and HITEC City enterprises.',
    keywords: [
      'Web Development Hyderabad',
      'Software Company HITEC City',
      'Mobile App Development Hyderabad',
      'IT Services Hyderabad'
    ],
    faqs: [
      {
        q: 'Can you handle enterprise healthcare or pharma software in Hyderabad?',
        a: 'Yes, we build secure, role-based portals with detailed audit trails and data encryption.',
      },
    ],
  },

  // ==========================================
  // 3. INTERNATIONAL COMMERCIAL HUBS
  // ==========================================
  {
    slug: 'dubai',
    city: 'Dubai',
    state: 'Dubai',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    region: 'Middle East',
    regionCode: 'AE-DU',
    coordinates: { latitude: 25.2048, longitude: 55.2708 },
    popular: true,
    headlineTitle: 'Premium web applications, luxury UI/UX and mobile apps in',
    headlineHighlight: 'Dubai, UAE',
    subheadline: 'Engineering bespoke e-commerce, real estate portals, and corporate digital experiences for fast-growing businesses across Dubai, Abu Dhabi, and the GCC.',
    aboutText: "We craft world-class digital products for the UAE and Middle East market. Our team delivers multilingual (Arabic/English) web applications, high-converting real estate portals, and iOS/Android mobile apps.",
    metaTitle: 'Web Development & Mobile App Company in Dubai, UAE | TryangleTech',
    metaDescription: 'Premier web design, custom software, and mobile app development agency in Dubai, UAE. High-converting Next.js websites and mobile applications.',
    keywords: [
      'Web Development Company Dubai',
      'Mobile App Development Dubai UAE',
      'Custom Software Company Dubai',
      'Real Estate Portal Development Dubai',
      'Ecommerce Web Design UAE'
    ],
    faqs: [
      {
        q: 'Do you build bilingual Arabic and English websites in Dubai?',
        a: 'Yes, we provide full RTL (Right-to-Left) Arabic interface support alongside seamless English localization.',
      },
      {
        q: 'How do you manage international time-zones for UAE clients?',
        a: 'Our team operates on overlapping Gulf Standard Time (GST) hours with dedicated project managers available on Slack, WhatsApp, and Google Meet.',
      },
    ],
  },
  {
    slug: 'london',
    city: 'London',
    state: 'Greater London',
    country: 'United Kingdom',
    countryCode: 'GB',
    region: 'Europe & UK',
    regionCode: 'GB-ENG',
    coordinates: { latitude: 51.5074, longitude: -0.1278 },
    popular: true,
    headlineTitle: 'Bespoke web development and custom software engineering in',
    headlineHighlight: 'London, UK',
    subheadline: 'Delivering modern full-stack web applications, FinTech platforms, and mobile apps for UK enterprises and scaling startups.',
    aboutText: "We provide high-caliber software engineering for London and UK businesses, combining British design sensibilities with agile, cost-effective full-stack execution.",
    metaTitle: 'Web Development & Custom Software Agency London, UK | TryangleTech',
    metaDescription: 'Trusted software engineering and web development agency for London and UK businesses. High-performance Next.js and mobile apps.',
    keywords: [
      'Web Development London UK',
      'Custom Software Development London',
      'Mobile App Developers UK',
      'Next.js Agency London',
      'IT Outsourcing UK'
    ],
    faqs: [
      {
        q: 'What are the cost benefits for UK businesses working with TryangleTech?',
        a: 'UK clients save up to 60% on development costs while receiving direct communication with senior engineers and guaranteed UK-standard quality.',
      },
    ],
  },
  {
    slug: 'new-york',
    city: 'New York',
    state: 'New York',
    country: 'United States',
    countryCode: 'US',
    region: 'USA & Canada',
    regionCode: 'US-NY',
    coordinates: { latitude: 40.7128, longitude: -74.0060 },
    popular: true,
    headlineTitle: 'High-performance web applications and custom software in',
    headlineHighlight: 'New York, USA',
    subheadline: 'Powering New York startups, commercial brands, and agencies with cutting-edge Next.js web applications, mobile apps, and cloud backend engineering.',
    aboutText: "We build scalable, high-converting digital products for the North American market. We help New York businesses automate workflows, launch mobile apps, and scale revenue.",
    metaTitle: 'Web Development & Custom Software Company in New York, USA | TryangleTech',
    metaDescription: 'Top-rated software and web development agency for New York businesses. Fast, secure, and custom-built digital solutions.',
    keywords: [
      'Web Development Company New York',
      'Custom Software Development NYC',
      'Mobile App Developers New York',
      'Next.js Agency USA',
      'React Native Developers NYC'
    ],
    faqs: [
      {
        q: 'How do you coordinate with EST (Eastern Standard Time) in New York?',
        a: 'We maintain daily overlapping US morning hours and provide continuous asynchronous sprint updates.',
      },
    ],
  },
  {
    slug: 'toronto',
    city: 'Toronto',
    state: 'Ontario',
    country: 'Canada',
    countryCode: 'CA',
    region: 'USA & Canada',
    regionCode: 'CA-ON',
    coordinates: { latitude: 43.6532, longitude: -79.3832 },
    popular: false,
    headlineTitle: 'Custom web software and mobile application development in',
    headlineHighlight: 'Toronto, Canada',
    subheadline: 'Engineering robust web platforms, automated business tools, and mobile apps for Canadian startups and commercial enterprises.',
    aboutText: "TryangleTech delivers enterprise software and digital growth platforms for Toronto and Canadian businesses, backed by 350+ successful launches.",
    metaTitle: 'Web Development & Custom Software in Toronto, Canada | TryangleTech',
    metaDescription: 'Leading web design and mobile app development company for Toronto, Canada. 350+ projects delivered.',
    keywords: [
      'Web Development Toronto',
      'Software Company Toronto Canada',
      'Mobile App Development Toronto',
      'IT Agency Ontario'
    ],
    faqs: [
      {
        q: 'Do you sign NDAs and provide code ownership to Canadian clients?',
        a: 'Yes, 100% intellectual property (IP) and code ownership belongs to you, protected by comprehensive NDAs.',
      },
    ],
  },
  {
    slug: 'sydney',
    city: 'Sydney',
    state: 'New South Wales',
    country: 'Australia',
    countryCode: 'AU',
    region: 'Global Hubs',
    regionCode: 'AU-NSW',
    coordinates: { latitude: -33.8688, longitude: 151.2093 },
    popular: false,
    headlineTitle: 'Modern web applications and mobile engineering in',
    headlineHighlight: 'Sydney, Australia',
    subheadline: 'Helping Australian businesses and startups build fast, reliable websites, iOS/Android apps, and custom business management software.',
    aboutText: "Serving Sydney, Melbourne, and Brisbane with high-performance web development, mobile apps, and dedicated software engineering squads.",
    metaTitle: 'Web Development & Mobile App Company in Sydney, Australia | TryangleTech',
    metaDescription: 'Trusted web design, mobile app, and custom software development company for Sydney, Australia.',
    keywords: [
      'Web Development Sydney',
      'Mobile App Developers Australia',
      'Custom Software Sydney',
      'IT Company Sydney NSW'
    ],
    faqs: [
      {
        q: 'How do you coordinate with Australian clients (AEST)?',
        a: 'We provide dedicated communication windows overlapping with Australian business hours for real-time progress reviews.',
      },
    ],
  },
  {
    slug: 'singapore',
    city: 'Singapore',
    country: 'Singapore',
    countryCode: 'SG',
    region: 'Global Hubs',
    regionCode: 'SG',
    coordinates: { latitude: 1.3521, longitude: 103.8198 },
    popular: false,
    headlineTitle: 'High-speed cloud platforms and mobile applications in',
    headlineHighlight: 'Singapore',
    subheadline: 'Delivering secure FinTech portals, corporate websites, and mobile applications for Singapore and Southeast Asian enterprises.',
    aboutText: "We bring 7+ years of engineering rigor to Singapore's premier digital market, delivering rapid, secure web applications and custom software.",
    metaTitle: 'Web & Mobile App Development Company in Singapore | TryangleTech',
    metaDescription: 'Enterprise web development, mobile apps, and custom software engineering for Singapore businesses.',
    keywords: [
      'Web Development Singapore',
      'Software Company Singapore',
      'Mobile App Development Singapore',
      'IT Services SG'
    ],
    faqs: [
      {
        q: 'What standards do you follow for enterprise software in Singapore?',
        a: 'We adhere to clean architecture, OWASP top-10 security guidelines, and microservice/serverless best practices.',
      },
    ],
  },
];
