import { HomeContentDTO } from './home.types';

export const DEFAULT_HOME_CONTENT: HomeContentDTO = {
  id: 'home_main_v1',
  hero: {
    subBadgeText: 'DIGITAL SOLUTIONS',
    headline: 'We build websites, apps and software that actually work for your business',
    subheadline: 'Whether you need a new website, a mobile app, or a complete software solution, our team in Ahmedabad has been helping businesses like yours grow online for over 7 years.',
    ctaText: 'Talk to us today',
    ctaLink: '/contact',
    floatingBadgeText: "Let's Build",
    dashboardImage: '/Taskopia_files/6915c8033293ed4e29e1f4ac_taskopia-hero-one-dashbord.avif',
    dashboardImageAlt: 'TryangleTech Digital Dashboard Solutions',
    avatars: ['#38bdf8', '#3b82f6', '#a855f7'],
    serviceBadges: [
      { text: 'Custom Web & Apps' },
      { text: 'UI/UX Design' },
      { text: 'Cloud & DevOps' },
      { text: 'SEO & Marketing' },
    ],
  },
  services: [
    {
      id: 'srv-1',
      title: 'Website Development',
      description: 'We build custom websites, WordPress sites, online stores, and business websites.',
      highlightText: 'Every site is fast, mobile-friendly, and built to convert.',
      pills: ['Custom Development', 'WordPress', 'E-Commerce', 'Responsive Design', 'Business Websites'],
      link: '/service/website-development',
    },
    {
      id: 'srv-2',
      title: 'Custom Software Development',
      description: 'From CRM systems and inventory management to custom internal tools, we engineer tailored software.',
      highlightText: 'Automate manual tasks and manage operations with zero fuss.',
      pills: ['CRM Systems', 'ERP Software', 'Business Automation', 'Cloud Software', 'Custom APIs'],
      link: '/service/custom-software',
    },
    {
      id: 'srv-3',
      title: 'Mobile App Development',
      description: 'We develop native and cross-platform mobile apps for Android and iOS using Flutter and React Native.',
      highlightText: 'Smooth performance, intuitive UX, and robust backend integrations.',
      pills: ['iOS Apps', 'Android Apps', 'Flutter', 'React Native', 'Cross-Platform'],
      link: '/service/mobile-app-development',
    },
    {
      id: 'srv-4',
      title: 'Digital Marketing & SEO',
      description: 'Get found by customers searching for your products and services with data-driven SEO & growth strategies.',
      highlightText: 'Drive real organic traffic and qualified business leads.',
      pills: ['Search Engine Optimization', 'Google Ads', 'Social Media', 'Content Marketing', 'Local SEO'],
      link: '/service/digital-marketing',
    },
  ],
  about: {
    subtitle: 'WHO WE ARE',
    heading: 'We build websites and apps that actually work for',
    headingHighlight: 'your business',
    description: "We're a tech team based in Ahmedabad. For over 7 years, we've helped Indian businesses launch websites, build mobile apps, and develop custom software that gets real results. You tell us what you need – we design it, build it, and launch it. No technical jargon, no disappearing acts.",
    features: [
      {
        id: 'feat-1',
        title: 'Consistent quality -',
        description: 'every project is tested and reviewed before it reaches you.',
        icon: '/Taskopia_files/6916f191d4b3b4e4b2cee5b2_Vector (35).svg',
      },
      {
        id: 'feat-2',
        title: 'Clear communication -',
        description: 'you always know where your project stands, with one point of contact keeping you updated.',
        icon: '/Taskopia_files/6916f191d4b3b4e4b2cee5b2_Vector (35).svg',
      },
    ],
    ctaText: 'Talk to us today',
    ctaLink: '/contact',
    image1: '/Taskopia_files/68ef7bedcf795a787addad8c_Group 2085663562.webp',
    image2: '/Taskopia_files/68ef7bed775c847e27d93569_Group 2085663563.webp',
  },
  whyChooseUs: {
    subtitle: 'WHY CHOOSE US',
    heading: 'Why 350+ businesses',
    headingHighlight: 'chose us',
    items: [
      {
        id: 'wcu-1',
        title: 'Built for your business',
        description: 'No templates, no copy-paste designs. Every site or app we build is planned around what your business sells and who your customers are.',
        icon: '/Taskopia_files/6916ef876682eed2b2fd5911_Vector (34).svg',
      },
      {
        id: 'wcu-2',
        title: 'We deliver on time',
        description: "When we quote a timeline, we stick to it - 2 to 4 weeks for a website, 4 to 8 for custom software. You'll get regular updates along the way.",
        icon: '/Taskopia_files/6916f00db3051e5aed09bd3f_Group 2085663576.svg',
      },
      {
        id: 'wcu-3',
        title: 'Real people, no jargon',
        description: 'We explain things simply and stay in touch throughout the project. You will always know what is happening without having to learn tech buzzwords.',
        icon: '/Taskopia_files/6916ec635353353be914aafc_Vector (32).svg',
      },
      {
        id: 'wcu-4',
        title: 'Support after launch',
        description: 'We do not disappear once your project is live. We help with updates, fixes, and support whenever you need it to keep everything running smoothly.',
        icon: '/Taskopia_files/6916ec63e8a4a58eb6e788ad_Vector (33).svg',
      },
    ],
    centerImage: '/Taskopia_files/691ecfdec4425f741cb80fc8_tasopiya-home-one-hande.webp',
  },
  howWeWork: {
    subtitle: 'HOW WE WORK',
    heading: 'How we work with you from start',
    headingHighlight: 'to finish',
    description: 'We start by listening to what you need. Then we plan, design, build, and launch your project. You are part of the process at every step, so there are never any surprises.',
    items: [
      {
        id: 'hww-1',
        title: 'Clear communication',
        description: 'You will have a dedicated point of contact who keeps you updated. No chasing for answers or wondering what is happening with your project.',
        icon: '/Taskopia_files/6916ed30eddd8192431b095e_specialiti-icon-1 (1).svg',
      },
      {
        id: 'hww-2',
        title: 'Proven track record',
        description: 'We have delivered over 350 websites and projects in the last 7 plus years. We know how to plan properly and launch on time.',
        icon: '/Taskopia_files/6916ed30605dc4748f8c24c3_specialiti-icon-2 (1).svg',
      },
    ],
    ctaText: 'Talk to us today',
    ctaLink: '/contact',
    image1: '/Taskopia_files/68f21b4dc6a06a6abe39c79b_taskopia-Collaboration-one.webp',
    image2: '/Taskopia_files/68f21b3af8e5e0af23ce678d_taskopia-Collaboration-two.webp',
    image3: '/Taskopia_files/68f21b3a3b734d2430609672_taskopia-Collaboration-three.webp',
  },
  techStack: [
    { id: 'tech-1', name: 'React', icon: '/tech-icons/react.svg', category: 'Frontend' },
    { id: 'tech-2', name: 'Next.js', icon: '/tech-icons/nextdotjs.svg', category: 'Frontend' },
    { id: 'tech-3', name: 'TypeScript', icon: '/tech-icons/typescript.svg', category: 'Frontend' },
    { id: 'tech-4', name: 'TailwindCSS', icon: '/tech-icons/tailwindcss.svg', category: 'Styling' },
    { id: 'tech-5', name: 'Node.js', icon: '/tech-icons/nodedotjs.svg', category: 'Backend' },
    { id: 'tech-6', name: 'Python', icon: '/tech-icons/python.svg', category: 'Backend' },
    { id: 'tech-7', name: 'Laravel', icon: '/tech-icons/laravel.svg', category: 'Backend' },
    { id: 'tech-8', name: 'Flutter', icon: '/tech-icons/flutter.svg', category: 'Mobile' },
    { id: 'tech-9', name: 'WordPress', icon: '/tech-icons/wordpress.svg', category: 'CMS' },
    { id: 'tech-10', name: 'PostgreSQL', icon: '/tech-icons/postgresql.svg', category: 'Database' },
    { id: 'tech-11', name: 'Amazon AWS', icon: '/tech-icons/amazonwebservices.svg', category: 'Cloud' },
    { id: 'tech-12', name: 'Figma', icon: '/tech-icons/figma.svg', category: 'Design' },
  ],
  testimonials: [
    {
      id: 'test-1',
      name: 'Jonathan Keller',
      title: '"Great experience working together"',
      text: '“We hired TryangleTech to rebuild our company website and the result was amazing. The team understood exactly what we needed and delivered a site that our customers love. Highly recommended.”',
      image: '/Taskopia_files/68f20568d8c28959fddbf700_taskopia-testimonials-author-v1.webp',
      rating: 5,
    },
    {
      id: 'test-2',
      name: 'Rebecca Lin',
      title: '"Professional and reliable"',
      text: '“Their digital marketing work helped us grow our online traffic significantly. They are easy to communicate with and always deliver on their promises. A solid team you can count on.”',
      image: '/Taskopia_files/68f20568de5d5f47117e47e5_taskopia-testimonials-author-v2.webp',
      rating: 5,
    },
    {
      id: 'test-3',
      name: 'Mark Wilson',
      title: '"Excellent app development"',
      text: '“They built a mobile app for our business that works beautifully on both Android and iOS. The whole process was smooth and the team was always available when we had questions.”',
      image: '/Taskopia_files/68f2056835f743b2678916ad_taskopia-testimonials-author-v3.webp',
      rating: 5,
    },
    {
      id: 'test-4',
      name: 'Sarah Jenkins',
      title: '"Exceeded our expectations"',
      text: '“The custom software they developed for us streamlined our entire workflow. The TryangleTech team was communicative, fast, and delivered an outstanding product.”',
      image: '/Taskopia_files/68f20568d8c28959fddbf700_taskopia-testimonials-author-v1.webp',
      rating: 5,
    },
    {
      id: 'test-5',
      name: 'David Wright',
      title: '"A true technology partner"',
      text: '“From UI/UX design to final deployment, their graphics and development teams were fantastic. They didn’t just build what we asked for—they helped us improve our initial idea.”',
      image: '/Taskopia_files/68f20568de5d5f47117e47e5_taskopia-testimonials-author-v2.webp',
      rating: 5,
    },
    {
      id: 'test-6',
      name: 'Emily Davis',
      title: '"Unmatched support and quality"',
      text: '“We’ve worked with several agencies before, but TryangleTech stands out. Their attention to detail and ongoing support is exactly what our growing startup needed.”',
      image: '/Taskopia_files/68f2056835f743b2678916ad_taskopia-testimonials-author-v3.webp',
      rating: 5,
    },
  ],
  ctaBanner: {
    subtitle: 'LET’S WORK TOGETHER',
    heading: 'Ready to build something amazing for your business?',
    description: 'Schedule a free 30-minute consultation with our lead software architects. No technical jargon, no obligations.',
    buttonText: 'Talk to us today',
    buttonLink: '/contact',
    contactEmail: 'admin@tryangletech.com',
    contactPhone: '+91 99099 00000',
  },
};
