import { ServiceMainContentDTO, ServicePageSummaryItem } from './services.types';

export const DEFAULT_SERVICES_LIST: ServicePageSummaryItem[] = [
  {
    id: 'service-main',
    slug: 'main',
    name: 'Main Services Overview',
    route: '/service',
    category: 'Core Service Hub',
    isMainPage: true,
    isPublished: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'service-web-dev',
    slug: 'web-development',
    name: 'Website & Web Application Development',
    route: '/service/web-development',
    category: 'Engineering & Web',
    isMainPage: false,
    isPublished: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'service-custom-software',
    slug: 'custom-software',
    name: 'Custom Software & Enterprise Solutions',
    route: '/service/custom-software',
    category: 'Enterprise Engineering',
    isMainPage: false,
    isPublished: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'service-mobile-app',
    slug: 'mobile-application',
    name: 'iOS & Android Mobile App Development',
    route: '/service/mobile-application',
    category: 'Mobile Applications',
    isMainPage: false,
    isPublished: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'service-graphics',
    slug: 'graphics-designing',
    name: 'Graphics Designing & UI/UX Experience',
    route: '/service/graphics-designing',
    category: 'Design & Visuals',
    isMainPage: false,
    isPublished: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'service-marketing',
    slug: 'digital-marketing',
    name: 'Digital Marketing & Growth Engineering',
    route: '/service/digital-marketing',
    category: 'Marketing & SEO',
    isMainPage: false,
    isPublished: true,
    updatedAt: new Date().toISOString(),
  },
];

export const DEFAULT_SERVICE_MAIN_CONTENT: ServiceMainContentDTO = {
  id: 'service-main',
  hero: {
    subBadgeText: 'Our Services',
    headline: 'Comprehensive Digital Solutions for Your Business Growth',
    subheadline:
      'From custom software to data-driven marketing, we provide end-to-end services designed to scale your business and drive innovation.',
    primaryBtnText: 'Get started today',
    primaryBtnLink: '/contact',
    secondaryBtnText: 'View portfolio',
    secondaryBtnLink: '/portfolio',
    trustBadges: ['Innovative Solutions', 'Expert Engineering', 'Client-Centric'],
    avatars: ['#38bdf8', '#3b82f6', '#a855f7'],
  },
  servicesList: [
    {
      id: 'card-custom-software',
      slug: 'custom-software',
      title: 'Custom Software Development',
      description:
        'We create custom software that fits exactly what your business needs. Our solutions help your team work faster and make growing your company a whole lot easier.',
      link: '/service/custom-software',
      images: [
        '/Home3_files/690dad3581daca3524776a8e_Taskopia-features-home-v3-1.webp',
        '/Home3_files/690dad35a7b833185701eb5a_Taskopia-features-home-v3-2.webp',
        '/Home3_files/690dad35827ba1e2631d6c09_Taskopia-features-home-v3-3.webp',
      ],
      icon: '/Home3_files/690d9fbfe8207af12de2d5dd_Vector 1553.svg',
      badge: 'Enterprise Architecture',
    },
    {
      id: 'card-web-dev',
      slug: 'web-development',
      title: 'Website Development',
      description:
        'Get a beautiful website that works perfectly on any device. We design and build online experiences that grab attention and turn your visitors into loyal customers.',
      link: '/service/web-development',
      images: [
        '/Home3_files/690dad35e28b189c556cc11e_Taskopia-features-home-v3-right.webp',
        '/Home3_files/690dad35e3ae72cf7cacc7f0_Taskopia-features-home-v3-5.webp',
        '/Home3_files/690dad3509f6f587288a12d7_Taskopia-features-home-v3-7.webp',
      ],
      icon: '/Home3_files/690dad352e3eaaf91d055fe5_Taskopia-features-home-v3-icon.webp',
      badge: 'Modern Next.js Stack',
    },
    {
      id: 'card-mobile-app',
      slug: 'mobile-application',
      title: 'Mobile Application',
      description:
        'Connect with your customers wherever they are through a custom mobile app. We take your app idea and build an amazing experience for both Apple and Android phones.',
      link: '/service/mobile-application',
      images: [
        '/Home3_files/690dad3581daca3524776a8e_Taskopia-features-home-v3-1.webp',
        '/Home3_files/690dad35a7b833185701eb5a_Taskopia-features-home-v3-2.webp',
        '/Home3_files/690dad35827ba1e2631d6c09_Taskopia-features-home-v3-3.webp',
      ],
      icon: '/Home3_files/690d9fbfe8207af12de2d5dd_Vector 1553.svg',
      badge: 'iOS & Android Native',
    },
    {
      id: 'card-graphics',
      slug: 'graphics-designing',
      title: 'Graphics Designing & UI/UX',
      description:
        'Make your brand stand out with stunning visuals that capture your unique identity. From beautiful logos and marketing materials to amazing user interfaces, our creative team designs everything you need to leave a lasting impression. We focus on blending beautiful aesthetics with smart functionality.',
      link: '/service/graphics-designing',
      images: [
        '/Home3_files/690dad3581daca3524776a8e_Taskopia-features-home-v3-1.webp',
        '/Home3_files/690dad35a7b833185701eb5a_Taskopia-features-home-v3-2.webp',
        '/Home3_files/690dad35827ba1e2631d6c09_Taskopia-features-home-v3-3.webp',
      ],
      icon: '/Home3_files/690d9fbfe8207af12de2d5dd_Vector 1553.svg',
      badge: 'Design Systems & 3D',
    },
    {
      id: 'card-marketing',
      slug: 'digital-marketing',
      title: 'Digital Marketing & Growth',
      description:
        'Grow your audience and increase your sales online. We put together complete marketing strategies that help your business get noticed by the right people at the right time.',
      link: '/service/digital-marketing',
      images: [
        '/Home3_files/690dad3581daca3524776a8e_Taskopia-features-home-v3-1.webp',
        '/Home3_files/690dad35a7b833185701eb5a_Taskopia-features-home-v3-2.webp',
        '/Home3_files/690dad35827ba1e2631d6c09_Taskopia-features-home-v3-3.webp',
      ],
      icon: '/Home3_files/690d9fbfe8207af12de2d5dd_Vector 1553.svg',
      badge: 'Performance & ROI',
    },
  ],
  highlights: {
    subBadgeText: 'Key Highlights',
    heading: 'Deliver excellence, drive innovation, achieve scale',
    imageMain: '/Home2_files/69254371136c64c2548fd85e_taskopiya-home-two-project-over.webp',
    imageSmall: '/Home2_files/6912cb4228402e3879fa5f10_taskopia-home-two-who.webp',
    pillars: [
      {
        id: 'pillar-1',
        title: 'Collaboration',
        description: 'Partner with our dedicated experts to turn your vision into scalable solutions.',
        icon: 'bar-chart',
      },
      {
        id: 'pillar-2',
        title: 'Innovation',
        description: 'Leverage cutting-edge technologies and creative strategies to stay ahead of the curve.',
        icon: 'zap',
      },
      {
        id: 'pillar-3',
        title: 'Efficiency',
        description: 'Optimize your digital presence with high-performance applications and platforms.',
        icon: 'clock',
      },
      {
        id: 'pillar-4',
        title: 'Security',
        description: 'Enterprise-grade protection, rigorous compliance, and secure data handling standards.',
        icon: 'shield',
      },
    ],
  },
  tools: {
    subBadgeText: 'integration',
    heading: 'Streamline workflows, save time,',
    headingHighlight: 'enhance performance',
    tools: [
      { id: 't-1', name: 'React', icon: '/tech-icons/react.svg', category: 'Frontend' },
      { id: 't-2', name: 'Next.js', icon: '/tech-icons/nextjs.svg', category: 'Framework' },
      { id: 't-3', name: 'PHP', icon: '/tech-icons/php.svg', category: 'Backend' },
      { id: 't-4', name: 'AWS', icon: '/tech-icons/aws.svg', category: 'Cloud' },
      { id: 't-5', name: 'Docker', icon: '/tech-icons/docker.svg', category: 'DevOps' },
      { id: 't-6', name: 'Laravel', icon: '/tech-icons/laravel.svg', category: 'Backend' },
      { id: 't-7', name: 'Tailwind CSS', icon: '/tech-icons/tailwind.svg', category: 'Styling' },
      { id: 't-8', name: 'Figma', icon: '/tech-icons/figma.svg', category: 'Design' },
      { id: 't-9', name: 'Google Ads', icon: '/tech-icons/google-ads.svg', category: 'Marketing' },
      { id: 't-10', name: 'Razorpay', icon: '/tech-icons/razorpay.svg', category: 'Fintech' },
      { id: 't-11', name: 'Meta', icon: '/tech-icons/meta.svg', category: 'Social' },
    ],
  },
  faqs: [
    {
      id: 'faq-1',
      q: 'What types of services do you offer?',
      a: 'We offer a comprehensive suite of digital services including Custom Software Development, Web and Mobile App Development, UI/UX Graphics Designing, and full-scale Digital Marketing strategies to help businesses grow.',
    },
    {
      id: 'faq-2',
      q: 'Do you provide custom software solutions?',
      a: 'Yes, we specialize in building custom software tailored exactly to your unique business needs, ensuring scalability, performance, and seamless integration with your existing workflows.',
    },
    {
      id: 'faq-3',
      q: 'How long does a typical project take?',
      a: 'Project timelines vary depending on the scope and complexity. A simple website might take a few weeks, while a complex mobile application or custom software platform can take several months. We provide detailed timelines during the discovery phase.',
    },
    {
      id: 'faq-4',
      q: 'Do you offer post-launch support?',
      a: 'Absolutely. We provide ongoing maintenance and support for all our projects to ensure your software remains up-to-date, secure, and performs optimally as your business grows.',
    },
    {
      id: 'faq-5',
      q: 'Can you help with digital marketing and SEO?',
      a: 'Yes! Our digital marketing team provides data-driven strategies including SEO, social media management, and paid advertising to boost your online visibility and drive measurable conversions.',
    },
  ],
  testimonials: [
    {
      id: 'test-1',
      name: 'Michael Vance',
      role: 'Chief Technology Officer',
      company: 'Apex Digital Global',
      avatar: '/Home2_files/6900857a13043eba725f30f1_kloudera-home-one-testimonial-client-image.webp',
      rating: 5,
      content:
        'TryangleTech transformed our digital workflow with seamless custom software development. Their engineering speed, attention to detail, and communication are second to none.',
    },
    {
      id: 'test-2',
      name: 'Sarah Jenkins',
      role: 'Head of Product',
      company: 'Nova Commerce',
      avatar: '/Home2_files/6900857a13043eba725f30f1_kloudera-home-one-testimonial-client-image.webp',
      rating: 5,
      content:
        'The mobile application they built exceeded all our user adoption targets in the first quarter. Clean codebase, prompt delivery, and highly responsive support.',
    },
    {
      id: 'test-3',
      name: 'David Patel',
      role: 'Founder & CEO',
      company: 'ScaleX Ventures',
      avatar: '/Home2_files/6900857a13043eba725f30f1_kloudera-home-one-testimonial-client-image.webp',
      rating: 5,
      content:
        'From brand identity design to high-converting Web development and SEO, TryangleTech provides an unmatched 360-degree tech partnership.',
    },
  ],
  metaTitle: 'Our Services | Web, Mobile, Custom Software & Marketing | TryangleTech',
  metaDescription:
    'Explore TryangleTech’s full spectrum of digital services: Web Development, Custom Software Engineering, iOS/Android Apps, UI/UX Graphics Designing, and Growth Marketing.',
  keywords: [
    'Digital Services',
    'Custom Software Development',
    'Web Development',
    'Mobile Application Development',
    'Graphics Design UI/UX',
    'Digital Marketing Agency',
    'TryangleTech Services',
  ],
  canonicalUrl: 'https://tryangletech.com/service',
  isPublished: true,
  updatedAt: new Date().toISOString(),
};
